services:
  front:
    build:
      context: ./vite-project
      dockerfile: ./dockerfile
    networks:
    - nat
    restart: always
    ports:
      - 80:80
  my-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      my-db:
        condition: service_healthy
    networks:
    - nat
    env_file:
      - .env
    #얘가 아까 application.yml의 환경변수인데 환경변수를 주입받지 못하고 있어요
  my-db:
    image: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10

    networks:
      - nat
networks:
  nat: