spring:
  datasource:
    url: jdbc:mysql://my-db:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD} #id pw 는 yml 에 직접적으로 작성하지 않고 환경변수에 넣어서 작성하는게 일반적입니다
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: laypersonSingingContest


server:
  servlet:
    context-path: /api